### ISSUE TITLE
 HA 104.2 breaks sonoff_lan_mode_r3 works fine in 103.4 and started working again when back to 103.4

### ISSUE THREAD

**Issue by trentjw** [mattsaxon/sonoff-lan-mode-homeassistant#19]
this is a on going issue that I recently opened and it still behaving exactly as it did before I install 104.2 and it finds one out of 16 devices and it is randomly selecting which device it finds after each reboot of the server not sure why my original issue was closed but it is premature in closing

**Comment by mattsaxon** [comment]
Do you have the latest version of this component installed? Myself and a number of the people on this thread find it fixed with the latest versions of HA and this component. Please post some additional information on versions, behaviour and logs

**Comment by trentjw** [comment]
yes however I reverted back to 103.6 its my production system so it going to be a couple of days for me to try 104.x

**Comment by mattsaxon** [comment]
@trentjw, any update on this?

**Comment by trentjw** [comment]
My system is still on 103.6 waiting for 105 before trying again
On Sat, Feb 1, 2020 at 2:29 PM -0700, "mattsaxon" <notifications@github.com> wrote:
Assigned #19 to @trentjw.

**Comment by trentjw** [comment]
installed 105 issue persists, I can manually switch them on or off at the button on the device and it shows up from unavailable to status  but cannot switch them in home assistant nor does it register it switching on or off

**Comment by trentjw** [comment]
ok with some fiddling had to block access to the internet for all my switches and reboot the router regained control of them will fiddle with some more test before I get confident on this

**Comment by mattsaxon** [comment]
Not sure what is going on with your devices. The latest firmware shouldn’t need internet access to be blocked. I’ve never had to block it.

Have you got the LAN mode slider in the ON position in eWeLink for all the switches?

**Comment by trentjw** [comment]
103.6 worked as it should ewelink was in normal mode never worked in lab mode tried many times but don't really care about ewelink more concerned with home assistant, this is what I found is if I restart home assistant all my devices quit responding then go to unavailable until I block their access to the internet and reboot my router they all come back to life I then can allow them internet access  and they function not sure how long before the would stop responding will check when I get home after work

On Thu, Feb 6, 2020 at 12:10 AM -0700, "mattsaxon" <notifications@github.com> wrote:

Not sure what is going on with your devices. The latest firmware shouldn’t need internet access to be blocked. I’ve never had to block it.

Have you got the LAN mode slider in the ON position in eWeLink for all the switches?

**Comment by mattsaxon** [comment]
Sorry this is not clear to me. Are you in DIY mode or eWeLink mode. I’m not asking if you are using eWeLink generally.

When you say ‘not using lab mode’ what do you mean?

**Comment by trentjw** [comment]
There is no diy mode I have to extract the API key and device id so I use it in LAN 

On Thu, Feb 6, 2020 at 11:44 AM -0700, "mattsaxon" <notifications@github.com> wrote:

Sorry this is not clear to me. Are you in DIY mode or eWeLink mode. I’m not asking if you are using eWeLink generally.
When you say ‘not using lab mode’ what do you mean?

**Comment by trentjw** [comment]
this is my configuation in Home assistant 
```
  - platform: sonoff_lan_mode_r3
    name: Livingroom_Light_Switch
    device_id: 10008aa344
    api_key: 537a6e24-6eac-45a2-88a4-d390beebxxxx
```
this worked as expected in 103.6 through both Home assistant and EWELink even when I rebooted the HA server and and it worked just fine either with internet blocked or allowed to access the internet. and my EWElink app has never worked in LAN mode only in its normal mode and only when I allowed access to the devices

**Comment by mattsaxon** [comment]
I've found the issue and am just testing a fix.

**Comment by trentjw** [comment]
Awesome news 

I've found the issue and am just testing a fix.

**Comment by mattsaxon** [comment]
Please try latest version of code. Reopen/comment here if you still have problems
